#!/usr/local/bin/php
<?

function cmd($cmd)
	{
		passthru($cmd);
		// echo $cmd."\n";
	}

if ($_SERVER['argv'][1] === '--noAutoAdd')
	{
		$msg = $_SERVER['argv'][2];
	}
elseif ($_SERVER['argc'] > 2)
	{
		$msg = array_pop($_SERVER['argv']);
		unset($_SERVER['argv'][0]);
		cmd ("git add ".join(' ', $_SERVER['argv']));
	}
else
	{
		exec("git config status.showUntrackedFiles", $output);
		if (join($output) == 'no') cmd("git add -u");
		else cmd ("git add -A");
		$msg = $_SERVER['argv'][1];
	}
cmd ("git commit -m \"$msg\"");
