#!/usr/local/bin/php
<?

function cmd($cmd)
	{
		passthru($cmd);
	}

array_shift($_SERVER['argv']);

while ($arg = array_shift($_SERVER['argv']))
	{
		if (strpos($arg, '-') === 0)
			$options[trim($arg, '-')] = true;
		else
			$notOptions[] = $arg;
	}

while ($t = array_shift($notOptions))
	{
		if (count($notOptions)) $paths[] = $t;
		else $msg = $t;
	}

$git = "git";
if ($options['common']) $git .= ' --git-dir=/.common';

if ($paths) cmd("$git add \"".join('" "', $paths).'"');
elseif (!$options['noAutoAdd'])
	{
		exec("$git config status.showUntrackedFiles", $output);
		if (join($output) == 'no') cmd("$git add -u");
		else cmd("$git add -A");
	}

cmd("$git commit -m \"$msg\"");
