#!/usr/local/bin/php
<?

function cmd($cmd)
	{
		passthru($cmd);
	}

array_shift($_SERVER['argv']);

while ($arg = array_shift($_SERVER['argv']))
	{
		if (strpos($arg, '-') === 0 && count($_SERVER['argv']))
			{
				$parts = explode('=', $arg, 2);
				$options[ltrim($parts[0], '-')] = $parts[1] ?? true;
			}
		else
			$notOptions[] = $arg;
	}

while ($t = array_shift($notOptions))
	{
		if (count($notOptions)) $paths[] = $t;
		else $msg = $t;
	}

$git = "git";
if ($options['common']) $git .= ' --git-dir=/.common';
elseif ($options['gitDir']) $git .= " --git-dir=/$options[gitDir]";

if ($paths) cmd("$git add \"".join('" "', $paths).'"');
elseif (!$options['noAutoAdd'])
	{
		exec("$git config status.showUntrackedFiles", $output);
		if (join($output) == 'no') cmd("$git add -u");
		else cmd("$git add -A");
	}

cmd("$git commit -m \"$msg\"");
