#!/usr/local/bin/php
<?

$db = $_SERVER['argv'][1];

if (!$db) exit;

$workDir = sys_get_temp_dir()."/$db";
if (is_dir($workDir)) exec("rm -rf $workDir");
mkdir($workDir);
exec("chmod o+xw $workDir");

if ($tableName = $_SERVER['argv'][2]) $tableName = ' '.$tableName;

exec("mysqldump --tab=$workDir --fields-terminated-by=',' $db$tableName");
$files = scandir($workDir);
$allSQL = "$workDir/$db.sql";
$fp = fopen($allSQL, 'w');
fwrite($fp, "SET FOREIGN_KEY_CHECKS=0;\n");

foreach ($files as $file)
	if (($pathinfo = pathinfo($file))['extension'] === 'sql')
		{
			fwrite($fp, file_get_contents("$workDir/$file")."\n");
			$tableName = $pathinfo['filename'];
			$dataFile = $pathinfo['filename'].'.txt';
			fwrite($fp, "LOAD DATA INFILE '/tmp/$db/$dataFile' INTO TABLE `$tableName` FIELDS TERMINATED BY ',';\n");
		}

fwrite($fp, "SET FOREIGN_KEY_CHECKS=1;");

exec("zip -jmT ".sys_get_temp_dir()."/$db.zip $workDir/$db.sql $workDir/*.txt");
exec("rm -rf $workDir");
