#!/usr/local/bin/php
<?

function cmd($cmd)
	{
		echo "\n$cmd";
		passthru($cmd);
	}

$dir = $hooksDir = dirname($_SERVER['SCRIPT_FILENAME']);

while ($dir = dirname($dir))
	{
		$isForca |= basename($dir) == 'Forca';
		if (is_dir("$dir/.git"))
			{
				$repoDir = $dir;
				break;
			}
	}

if (!$repoDir) return;

if (file_exists($forcaStartPath = "$repoDir/Forca/.php"))
	{
		cmd("unset GIT_DIR && cd $repoDir && git init && git config core.filemode false");
		cmd("unset GIT_DIR && cd $repoDir/Forca && git init && git config core.filemode false");
		cmd("$hooksDir/post-checkout");
		cmd("php $forcaStartPath upgrade/post-merge isForca=$isForca");
	}
