#!/usr/local/bin/php
<?

$repoRoot = dirname($_SERVER['SCRIPT_FILENAME'])."/../..");
if (file_exists($cmsPath = "$repoRoot/Forca/.php")
		|| file_exists($cmsPath = "$repoRoot/../Forca/.php"))
	passthru("php $cmsPath upgrade/post-merge");
