#!/usr/local/bin/php
<?

$hooksDir = dirname($_SERVER['SCRIPT_FILENAME']);
$isForca = strpos($hooksDir, $str = '.git/modules/Forca/hooks') === strlen($hooksDir) - strlen($str);
$repoRoot = $isForca ? "$hooksDir/../../../.." : "$hooksDir/../..";

if (file_exists($cmsPath = "$repoRoot/Forca/.php"))
	passthru("php $cmsPath upgrade/post-merge isForca=$isForca");
