#!/usr/local/bin/php
<?

$dir = $_SERVER['PWD'];
if ($subdir = $_SERVER['GIT_PREFIX']) $dir = explode('/'.rtrim($subdir, '/'), $dir, 2)[0];
if (strpos($dir, '/F/') !== 0) return;
exec("chown -R www-data:www-data $dir");