#!/usr/local/bin/php
<?

$dir = $_SERVER['PWD'];
if ($subdir = $_SERVER['GIT_PREFIX']) $dir = explode('/'.rtrim($subdir, '/'), $dir, 2)[0];
if (!preg_match("~^/F/[^/]+~", $dir, $m)) return;
if (!is_dir("$m[0]/Forca")) return;

if (is_dir(trim(exec("git rev-parse --git-path rebase-merge")))
		|| is_dir(trim(exec("git rev-parse --git-path rebase-apply"))))
	return;

$u = $g = 'www-data';
echo "setting ownership to $u:$g\n";

exec("chown -R $u:$g $dir");