#!/usr/local/bin/php
<?

git log --after=date("Y-n-d 00:00", $from) --before=date("Y-n-d 00:00", $to)

git checkout $from
git checkout -b sq
git merge --squash $to
commit "$fromName-$toName"
git rebase --onto sq $to $masterHead
git update-ref refs/heads/sq HEAD
git checkout sq
git branch -D master
git branch -m sq master
